"""Starter configuration template for ProFiles configuration files.

This module provides the canonical YAML template for ProFiles
configuration files. It is used by ``write_starter_config()`` and
``init_default_config()`` to generate fresh ``.profiles`` files.
"""

# Template for a freshly-generated starter .profiles. `{cwd}` is
# replaced with the current working directory at write time.
STARTER_CONFIG_TEMPLATE = """# ProFiles — Starter Configuration
# ============================================================================
# This file was generated by ProFiles on first launch. Every key matches
# the default value produced when no .profiles is present, so the GUI
# behaves identically with or without this file.
#
# ProFiles searches for ".profiles" starting at the current working
# directory (CWD) and walking its subdirectories. The first hit wins.
# If none is found anywhere, defaults are used (same as this starter).
#
# Booleans use YAML true/false. Lists are YAML arrays.
# ============================================================================

# ============================================================================
# CLI FLAGS
# ============================================================================
#   python -m profiles                          # GUI; reads this file
#   python -m profiles --config PATH/.profiles  # explicit config file
#   python -m profiles --headless               # CLI / no GUI
#   python -m profiles --init                   # regenerate this starter
# ============================================================================

# ============================================================================
# SEARCH OPERATORS (Extension + Filter fields in the GUI)
# ============================================================================
# Both fields are EDITABLE. You can also type a Google-style expression:
#   -        NOT / minus    "Prod -backup"          rejects files containing "backup"
#   +        include        "+Prod"                 explicit inclusion (= plain)
#   OR       alternation    "Prod OR Dev"           accepts either term
#   "..."    exact phrase   '"V2026.7"'             quotes a literal substring
#   space    implicit AND   "Production Program"    both terms must match (AND)
#
# Precedence (highest first):
#   1. Quoted phrases  -> one literal term
#   2. - or + prefix   -> binds to the immediately following term
#   3. Space (AND)     -> all terms in a group must match
#   4. OR              -> separates alternative groups
#
# The Extension field matches the full file suffix (no leading dot
# required). The Filter field matches the filename with extension.
# All comparisons are case-insensitive.
# ============================================================================

version: 1

# ============================================================================
# DEFAULTS — global values inherited by every configuration below.
# ============================================================================
# title:                string, default "" — optional text appended to the window title.
# gui_auto_launch:      bool, default true — show the GUI on `python -m profiles`.
# close_after_execute:  bool, default false — close the window after a launch.
# theme:                "light" | "dark" — Material Design 3 color theme.
# language:             "en" | "fr" — interface language.
# search_dir:           absolute path, default "{cwd}" — default value of the
#                       Directory field in the GUI.
# recursive_search:     bool, default false — initial state of the Recursive
#                       checkbox (search subdirectories too).
# extensions:           Extension combobox presets (fallback for per-config keys).
#                       "" or "All" = show all files; no leading dot required.
# filters:              Filter combobox presets ("" = show all files). Each preset may
#                       be a Google-style expression — see SEARCH OPERATORS above.
# row_colors:           generic row-coloring rules applied to ALL configurations.
#                       File rows whose name contains `pattern` (case-insensitive)
#                       are colored with `color` (#RRGGBB). Per-config row_colors are
#                       APPENDED to this base list and are checked first.
# search_exclude_dirs:  directory basenames (case-insensitive glob/wildcard patterns,
#                       e.g. `*tmp`, `node_modules`, `Debug*`) skipped during a
#                       recursive scan.
# search_exclude_files: filename glob patterns (case-insensitive) for files to skip
#                       during scanning. Per-config entries are APPENDED.
# verbose:              logging verbosity — "DEBUG" | "INFO" | "WARNING" | "ERROR" | "CRITICAL".
# scan_metrics:         bool, default false — log performance metrics after each scan.
# ============================================================================
defaults:
  title: ""
  gui_auto_launch: true
  close_after_execute: false
  theme: auto            # "light" or "dark" or "auto"
  language: en            # "en" or "fr"
  search_dir: '{cwd}'
  recursive_search: false
  extensions: [All, .lnk]
  filters: ["", ST_PRO, ST_ENG]
  row_colors:
    - pattern: TMP
      color: "#BAC015"
    - pattern: DEV
      color: "#C01565"
  search_exclude_dirs: [.git, .*, __pycache__, bin, obj, tmp, Obsolete, Debug]
  search_exclude_files: []
  verbose: INFO            # DEBUG | INFO | WARNING | ERROR | CRITICAL
  scan_metrics: false

# ============================================================================
# COLUMNS — dynamic columns extracted from filenames via regex.
# Expressions are applied to the FULL FILE PATH, enabling extraction of
# Path, FileName, Directory, and other path components.
# The "File" column is implicit and always appears first.
#
# Keys per column:
#   width       int     default 150    column width in pixels
#   expression  regex   required       pattern applied to the full file path
#   group       int     default 1      regex group to extract (0=full match,
#                                      1+=captured group)
#   priority    int     default 0      extraction priority (higher = first)
#   default     string  optional       value used when the pattern doesn't match
# ============================================================================
columns:
  File:
    width: 600
    expression: '.*'
    group: 0
    priority: 100
    default: ""
  Path:
    width: 200
    expression: '(.+[\\\\/])'
    group: 1
    priority: 40
    default: "."
  FileName:
    width: 150
    expression: '([^/\\\\]+)$'
    group: 1
    priority: 30
  Type:
    width: 80
    expression: "(PRO|ENG|DEV|TMP|DEBUG)(?!.*(?:PRO|ENG|DEV|TMP|DEBUG))"
    group: 1
    priority: 20
  Version:
    width: 100
    expression: '[-_]V(\\\\d+(?:\\\\.\\\\d+)*)(?=[^\\\\/]*\\\\.[a-zA-Z0-9]+$)'
    group: 1
    priority: 10

# ============================================================================
# HOOKS — step-based workflows for file launches.
# ============================================================================
# Execute a sequence of steps before, instead of, or after a file launch.
# Keys are GLOB PATTERNS (exact name, wildcard, or extension).
# The most specific pattern matches (e.g., `special.mttl` wins over `*.mttl`).
#
# Patterns supported:
#   *             star (any characters) — e.g., `*.pdf`, `report_*.pdf`
#   ?             single character — e.g., `test?.txt`
#   .ext          shorthand for `*.ext` — e.g., `.mttl`
#   filename.ext  exact match — e.g., `manual.pdf`
#
# Steps within an entry are YAML objects with:
#   action      "notify" | "run" | "run_after" | "replace" | "check"
#               (required) — see ACTIONS below.
#   content     the command template or notification message (tokens supported).
#   ask         string, optional — a yes/skip/no confirmation message.
#               (Yes -> run step; Skip -> proceed to NEXT step; No -> ABORT).
#   wait        bool, default true — wait for command completion.
#   on_failure  "stop" | "warn" | "continue" (default "stop").
#
# ACTIONS:
#   notify      Show a message to the user. Supports simple Markdown (**bold**,
#               *italic*, # heading).
#   run         Execute a shell command.
#   run_after   Spawn a command in the background (asynchronous).
#   replace     Execute a command instead of the standard OS launch. If a
#               workflow reaches a 'replace' step, the OS launch is SKIPPED.
#   check       Execute a command and check return code.
#
# TOKENS (substituted at runtime):
#   {{path}}       absolute file path                    {{dir}}   parent directory
#   {{filename}}   file name (with extension)            {{ext}}   extension (e.g. ".mttl")
#   {{stem}}       file name without extension
#
# failmode: "warn" | "abort" | "skip" — behavior for failing 'before' steps.
# timeout: seconds for blocking steps.
# ============================================================================
hooks:
  failmode: warn           # "warn" | "abort" | "skip"
  timeout: 30
  entries:
    # ".mttl":
    #   - action: notify
    #     content: "# Launching {{filename}}\\nPreparing environment..."
    #   - action: run
    #     content: "prepare.exe --file {{path}}"
    #     ask: "Run preparation script?"
    #   - action: replace
    #     content: "special_launcher.exe {{path}}"
    #     ask: "Use special launcher instead of OS default?"
    # ".pdf":
    #   - action: run_after
    #     content: "logger.exe --opened {{filename}}"

# ============================================================================
# CONFIGS — named configurations. Each may `extends` another config.
# The name is the dict key. `pc_hostname: All` acts as a catch-all — place
# it LAST so it does not shadow specific hostnames.
#
# Keys (all optional, except pc_hostname if you want auto-selection):
#   extends       name of another config to inherit from (lists are merged:
#                 local items first, then inherited items not already present)
#   pc_hostname   local hostname this config targets (exact, case-insensitive)
#                 or "All" for a catch-all
#   pc_ip         display-only IP label (NOT used for matching)
#   pc_name       friendly label (logs, status)
#   directory     production directory scanned for this machine
#                 ("" = inherits search_dir)
#   extensions    per-config Extension presets (overrides defaults)
#   filters       per-config Filter presets (overrides defaults)
#   row_colors    per-config row-coloring rules (APPENDED to defaults,
#                 checked first)
#   search_exclude_files  per-config file excludes (APPENDED to defaults)
#
# row_colors from the config whose `directory` matches the selected
# directory are applied automatically, even if the hostname doesn't match.
# ============================================================================
configs:
  base:
    pc_name: Generic
    directory: '{cwd}'
    row_colors:
      - pattern: SPECIFIC
        color: "#FF0000"

  # production:
  #   extends: base
  #   pc_hostname: COMPUTER-1
  #   pc_ip: 172.16.40.143
  #   extensions: [.pdf, .docx, .lnk, .xlsx]
  #   filters: [tmp, dev, prod]

# ============================================================================
# TIPS
# ============================================================================
#   * Launch ProFiles once with --init to regenerate this starter.
#   * The Directory combobox in the GUI defaults to CWD until you set
#     `search_dir` here or add a matching config.
#   * `extensions` / `filters` in `defaults` are FALLBACKS only; a
#     per-config entry overrides them for the matching station.
#   * `row_colors` in `defaults` provide a BASE set of rules; per-config
#     `row_colors` are APPENDED and have priority (checked first).
#   * When you change the Directory in the GUI, the row_colors from the
#     config whose `directory` matches the selected directory are applied
#     automatically, even if the hostname doesn't match.
"""
